pipeline:

  build:
    image: golang
    commands:
      - go build 
      - go test

  docker:
    image: plugins/docker
    repo:  codekube/drone-with-go
    tags: "${DRONE_COMMIT_SHA:0:8}"
    secrets: [ docker_username, docker_password ]

